name: 'Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:  # to run it manually
    inputs:
        tf_command:
          description: 'TerraForm command to run'
          type: choice
          required: true
          options:
            - apply
            - destroy

permissions:
  contents: read

jobs:
  plan:
    name: 'Planning the deployment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: |
            cd iac/prd
            terraform init
          env:
            TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        
        - name: Terraform Plan
          run: |
            cd iac/prd
            terraform plan
          env:
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  deploy:
    name: 'Deploying on AWS'
    needs: [ plan ]
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: |
          cd iac/prd
          terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      
      - if: github.event.inputs.tf_command == 'apply' || ! github.event.inputs.tf_command
        name: Terraform Apply
        run: |
          cd iac/prd
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - if: github.event.inputs.tf_command == 'destroy'
        name: Terraform Destroy
        run: |
          cd iac/prd
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
