name: 'Deploy'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploying on AWS'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Create ZIP for lambda code
          run: |
            chmod 744 ./scripts/build_lambda.py
            ./scripts/build_lambda.py

        - name: Debug pwd
          run: |
            pwd
            ls -ls ./src/language-detector/

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: |
            cd iac/prd
            terraform init
        
        - name: Terraform Plan
          run: |
            cd iac/prd
            terraform plan
          env:
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"