name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      tf_command:
        description: 'Terraform command to run'
        required: true
        default: 'destroy'
        type: choice
        options:
          - apply
          - destroy
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  plan:
    name: 'Planning the deployment'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Create ZIP for lambda code
          run: |
            chmod 744 ./scripts/build_lambda.py
            ./scripts/build_lambda.py

        - name: Debug
          run: |
            ls -ls ./src/language-detector/python

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        - name: Terraform Init
          run: |
            cd iac/prd
            terraform init
          env:
            TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        
        - name: Terraform Plan
          run: |
            cd iac/prd
            terraform plan
          env:
            AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

  deploy:
    name: 'Deploying on AWS'
    needs: [ plan ]
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ZIP for lambda code
        run: |
          chmod 744 ./scripts/build_lambda.py
          ./scripts/build_lambda.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: |
          cd iac/prd
          terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      
      - name: Terraform Apply
        if: ${{ inputs.tf_command }} == 'apply'
        run: |
          cd iac/prd
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}

      - name: Terraform Destroy
        if: ${{ inputs.tf_command }} == 'destroy'
        run: |
          cd iac/prd
          terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
